config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords, :sessions]
  as :user do
    post 'sign_in', to: 'sessions#create', as: :user_session
    delete 'sign_out', to: 'sessions#destroy', as: :destroy_user_session
    get 'settings', to: 'users#settings'
    get 'update_password', to: 'users#settings'
    patch 'update_password', to: 'users#update_password'
  end

  resources :tournaments do
    resources :groups, shallow: true
  end

  resources :groups do
    member do
      put 'update_teams'
      get 'search_teams'
    end
  end

  resources :teams do
    put 'update_players', on: :member
  end

  resources :players do
    get 'autocomplete', on: :collection
  end

  resources :faqs, except: [:show] do
    put 'order', on: :collection
  end

  get 'sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

  resources :pages, except: [:index, :show]
  get '/:id', to: 'pages#show', as: :to_page

  root to: 'tournaments#index'
end

app/models/faq.rb
class Faq < ApplicationRecord
  after_initialize :set_default_order, if: :new_record?
  validates_presence_of :question, :answer, :order

  def set_default_order
    self.order ||= 0
  end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:edit, :update, :destroy]

  def index
    @faqs = Faq.all.order(:order)
  end

  def new
    @faq = Faq.new
  end

  def edit
  end

  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to faqs_url, notice: t('controllers.faq.create') }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to faqs_url, notice: t('controllers.faq.update') }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: t('controllers.faq.destroy') }
      format.json { head :no_content }
    end
  end

  def order
    order, total = params[:order], Faq.count
    if order.is_a?(Array) && order.size == total
      Faq.update order.map(&:to_i), (1..total).map { |n| {order: n} }
    end
    head :no_content
  end

  private
    def set_faq
      @faq = Faq.find(params[:id])
    end

    def faq_params
      params.require(:faq).permit(:question, :answer, :order)
    end
end

app/views/faqs/_form.html.slim
= bootstrap_form_for @faq, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-10' do |f|
  = f.text_field :question, autofocus: true, placeholder: t('views.faqs.edit.placeholders.question')
  = f.text_area :answer, placeholder: t('views.faqs.edit.placeholders.answer')
  = f.form_group do
    = f.submit t('helpers.links.save'), class: 'btn btn-primary'
    = link_to t('.cancel', default: t('helpers.links.cancel')), faqs_path, class: 'btn'

- content_for :js_footer do
  javascript:
    new SimpleMDE({ spellChecker: I18n.locale === 'en' });

app/views/faqs/edit.html.slim
.page-header
  h1
    =t 'views.faqs.edit.title'
    .pull-right
      = faqs_header_glyph

== render 'form'

app/views/faqs/index.html.slim
.page-header
  h1
    =t 'gen.faqs'
    .pull-right
      = faqs_header_glyph

- if can? :create, Faq
  .actions.text-right style='margin: 10px;'
    = link_to new_faq_path, class: 'btn btn-circle', title: t('views.faqs.tooltips.new') do
      = add_glyph

.panel-group.draggable id='accordion'
  - @faqs.each_with_index do |faq, index|
    .panel.panel-info id="#{faq.id}"
      .panel-heading
        h4.panel-title.clearfix
          a data-toggle='collapse' data-parent='#accordion' href="#collapse#{index}"
            = faq.question
            - if can? :manage, Faq
              .pull-right.actions

                => link_to edit_faq_path(faq), class: 'btn btn-circle', title: t('views.faqs.tooltips.edit')
                  = edit_glyph

                => link_to faq_path(faq), class: 'btn btn-red btn-circle', method: :delete,
                  data: { confirm: t('views.faqs.confirm_delete') }, title: t('views.faqs.tooltips.delete')
                  = delete_glyph

                i.fa.fa-bars.bars

      .panel-collapse.collapse id="collapse#{index}"
        .panel-body
          = markdown faq.answer

- can?(:manage, Faq) && content_for(:js_footer) do
  javascript:
    new Ordering({ sortable: '#accordion', element: '.panel', url: "#{order_faqs_path}" })

app/views/faqs/new.html.slim
.page-header
  h1
    =t 'views.faqs.new.title'
    .pull-right
      = faqs_header_glyph

= render 'form'