config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords, :sessions]
  as :user do
    post 'sign_in', to: 'sessions#create', as: :user_session
    delete 'sign_out', to: 'sessions#destroy', as: :destroy_user_session
    get 'settings', to: 'users#settings'
    get 'update_password', to: 'users#settings'
    patch 'update_password', to: 'users#update_password'
  end

  resources :tournaments do
    resources :groups, shallow: true
  end

  resources :groups do
    member do
      put 'update_teams'
      get 'search_teams'
    end
  end

  resources :teams do
    put 'update_players', on: :member
  end

  resources :players do
    get 'autocomplete', on: :collection
  end

  resources :faqs, except: [:show] do
    put 'order', on: :collection
  end

  get 'sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

  resources :pages, except: [:index, :show]
  get '/:id', to: 'pages#show', as: :to_page

  root to: 'tournaments#index'
end

app/models/tournament.rb
class Tournament < ApplicationRecord
  has_many :groups, dependent: :destroy

  after_initialize :set_default_attributes, if: :new_record?

  validates :title, presence: true
  validates :date, presence: true,
    inclusion: {
      in: Date.new(1990,1,1)...Date.new(Date.current.year + 2, 1, 1),
      message: I18n.t('activerecord.errors.messages.year_between', min: 1990, max: Date.current.year + 1)
    },
    format: {
      with: /(19|20)\d{2}/i,
      message: I18n.t('activerecord.errors.messages.four_digit_year')
    },
    uniqueness: true

  scope :recent, ->(n) { order(:date).last(n) }

  private

  def set_default_attributes
    self.date ||= Date.today.strftime('%Y-%m-%d')
  end
end

app/models/trail/tournament.rb
class Trail::Tournament < Tournament
  self.table_name = 'trail_tournaments'

  belongs_to :tournament, optional: true
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :store_per_page, only: [:index]
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.order(:date).reverse_order.page(params[:page]).per(params[:per])
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @tournament_groups = @tournament.groups.order(:name)
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: t('controllers.tournament.create') }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: t('controllers.tournament.update') }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: t('controllers.tournament.destroy') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:title, :description, :date)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.slim
= bootstrap_form_for @tournament, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-10' do |f|
  = f.text_field :title, autofocus: true, placeholder: t('views.tournaments.edit.placeholders.title')
  = f.text_area :description, placeholder: t('views.tournaments.edit.placeholders.description')
  = f.text_field :date, class: 'datepicker', control_col: 'col-sm-3', icon: 'th'
  = f.form_group do
    = f.submit t('helpers.links.save'), class: 'btn btn-primary'
    = link_to t('.cancel', default: t('helpers.links.cancel')), tournaments_path, class: 'btn'

- content_for :js_footer do
  javascript:
    new SimpleMDE({ spellChecker: I18n.locale === 'en' }); // uses first text area, i.e. description
    $('.datepicker').flatpickr({});

app/views/tournaments/_list.html.slim
= hidden_field_tag :per, params[:per]

- tournaments.each do |tournament|
  .col-xs-12
    .card
      .thumbnail
        .caption
          = link_to tournament_path(tournament)
            h6
              .small.pull-right
                = l tournament.date, format: :long
            h4
              = tournament.title
            = markdown tournament.description
            hr.ball
            - if can? :manage, Tournament
              .text-center.actions
                => link_to edit_tournament_path(tournament), class: 'btn btn-circle', title: t('views.tournaments.tooltips.edit')
                  = edit_glyph

                => link_to tournament_path(tournament), class: 'btn btn-red btn-circle', method: :delete,
                  data: { confirm: t('views.tournaments.confirm_delete') }, title: t('views.tournaments.tooltips.delete')
                  = delete_glyph

- if tournaments.empty?
  | Tournaments not found

app/views/tournaments/edit.html.slim
- breadcrumb :tournament, @tournament

.page-header
  h1
    =t 'views.tournaments.edit.title'
    .pull-right
      = tournament_header_glyph
= render partial: 'form'

app/views/tournaments/index.html.slim
- resource = Tournament.model_name.plural
.page-header
  h1
    =t 'gen.tournaments'
    .pull-right
      = tournament_header_glyph

- if can? :create, Tournament
  .actions.text-right style='margin: 10px;'
    = link_to new_tournament_path, class: 'btn btn-circle', title: t('views.tournaments.tooltips.new') do
      = add_glyph

.row id="#{resource}"
  = render 'list', tournaments: @tournaments

.row.remote_pagination
  = render 'shared/pagination_with_per_page_links', list: @tournaments, opts: {params: params.slice(:search).to_unsafe_h, remote: true, per_pages: [1, 8, 20]}

app/views/tournaments/index.js.slim
| $('#tournaments').html('
= j render 'list', tournaments: @tournaments
|');

| $('.remote_pagination').html('
= render 'shared/pagination_with_per_page_links', list: @tournaments, opts: { params: params.slice(:search).to_unsafe_h, remote: true, per_pages: [1, 8, 20] }
| ');

app/views/tournaments/new.html.slim
- breadcrumb :new_tournament

.page-header
  h1
    =t 'views.tournaments.new.title'
    .pull-right
      = tournament_header_glyph
= render partial: "form"

app/views/tournaments/show.html.slim
- breadcrumb :tournament, @tournament

- model_class = Tournament
.page-header
  h1
    .pull-right
      = tournament_header_glyph
    = @tournament.title

.actions
  => link_to tournaments_path, class: 'btn btn-circle', title: t('views.tournaments.tooltips.index')
    = back_glyph

  - if can? :manage, Tournament
    .pull-right
      => link_to edit_tournament_path(@tournament), class: 'btn btn-circle', title: t('views.tournaments.tooltips.edit')
        = edit_glyph

      => link_to tournament_path(@tournament), class: 'btn btn-red btn-circle', method: :delete,
        data: { confirm: t('views.tournaments.confirm_delete') }, title: t('views.tournaments.tooltips.delete')
        = delete_glyph

      => link_to new_tournament_path, class: 'btn btn-circle', title: t('views.tournaments.tooltips.new') do
        = add_glyph

      => link_to new_tournament_group_path(@tournament), class: 'btn btn-circle', title: t('views.tournaments.tooltips.new_group')
        = add_group_glyph

br

.card
  .thumbnail
    .caption
      h6
        .small.pull-right
          = l @tournament.date, format: :long
      = markdown @tournament.description

- @tournament_groups.each do |group|
  .card
    .thumbnail
      .caption
        h4
          = group.name
          - if can? :manage, Group
            .actions.pull-right
              => link_to edit_group_path(group), class: 'btn btn-circle', title: t('views.groups.tooltips.edit')
                = edit_glyph

              => link_to group_path(group), class: 'btn btn-red btn-circle', method: :delete,
                data: { confirm: t('views.groups.confirm_delete') }, title: t('views.groups.tooltips.delete')
                = delete_glyph

        = react_component 'App.Tournament.Group.Teams', { editable: can?(:manage, Group), teams: group.teams.map { |p| {id: p.id, name: p.name, avatar: p.avatar.url(:thumb)} } }