config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords, :sessions]
  as :user do
    post 'sign_in', to: 'sessions#create', as: :user_session
    delete 'sign_out', to: 'sessions#destroy', as: :destroy_user_session
    get 'settings', to: 'users#settings'
    get 'update_password', to: 'users#settings'
    patch 'update_password', to: 'users#update_password'
  end

  resources :tournaments do
    resources :groups, shallow: true
  end

  resources :groups do
    member do
      put 'update_teams'
      get 'search_teams'
    end
  end

  resources :teams do
    put 'update_players', on: :member
  end

  resources :players do
    get 'autocomplete', on: :collection
  end

  resources :faqs, except: [:show] do
    put 'order', on: :collection
  end

  get 'sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

  resources :pages, except: [:index, :show]
  get '/:id', to: 'pages#show', as: :to_page

  root to: 'tournaments#index'
end

app/views/shared/_avatar_chooser.html.slim
.text-center
  .thumbnail.avatar-border
    label.avatar-cropper href='#'
      div class='avatar' style="width:#{model.geometry(:thumb).width}px; height:#{model.geometry(:thumb).height}px; overflow:hidden"
        = image_tag model.avatar.url(:thumb)
    .caption
      label.btn.btn-default.btn-file
        input.avatar-chooser name="#{form.object_name}[avatar]" type='file' style='display: none;' accept="image/*"
          = t('views.avatar.upload')

- %w(crop_x crop_y crop_w crop_h crop_r).each do |attribute|
  = form.hidden_field attribute, id: attribute

.cropper.modal.fade role='dialog' tabindex='-1'
  .modal-dialog role='document'
    .modal-content
      .modal-header
        .button.close data-dismiss='modal'
          | &times;
        h4.modal-title
          = t('views.avatar.edit.title')

      .modal-body
        .text-center
          = image_tag model.avatar.url(:original), class: 'img-box', style: 'max-width: 100%;'

      .modal-footer
        .pull-left.text-left.help-block
          = simple_format t('views.avatar.edit.instructions')
        button.btn.btn-primary.modal-close.finish-crop.pull-right data-dismiss='modal'
          = t('views.avatar.edit.finish')

- content_for :js_footer do
  javascript:
    new ImageCropper({
      width:  "#{model.geometry(:thumb).width}",
      height: "#{model.geometry(:thumb).height}",
      avatar: $('.avatar'),
      image:  $('.img-box'),
      save: function(coords) {
        $("#crop_x").val(coords.x);
        $("#crop_y").val(coords.y);
        $("#crop_w").val(coords.w);
        $("#crop_h").val(coords.h);
        $("#crop_r").val(coords.r);
      }
    })

app/views/shared/_footer.html.slim
.row.col-md-12.text-center
  .col-sm-4
    .help.small
      => link_to t('gen.faqs'), faqs_path
      => link_to t('gen.about'), to_page_path('about')
      => link_to t('gen.contact'), to_page_path('contact')
  .copyright.col-sm-4
    .small
      | &copy; #{ Date.today.year } Cybfootball. All rights reserved.
    = link_to root_path
      image.img-circle src='/images/logo.jpg'

  .social-media.col-sm-4.hidden-xs
    a href='https://github.com/veelenga/cybfootball' target='_blank' title='Github'
      i.fa.fa-github.fa-2x
    a href='https://www.facebook.com/groups/341895829498550/' target='_blank' title='Facebook'
      i.fa.fa-facebook.fa-2x
    a href='https://twitter.com/cybfootball' target='_blank' title='Twitter'
      i.fa.fa-twitter.fa-2x

app/views/shared/_ga.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-63584551-5', 'auto');
  ga('send', 'pageview');

app/views/shared/_js_locale.html.slim
javascript:
  I18n.defaultLocale = "#{ I18n.default_locale }";
  I18n.locale = "#{ I18n.locale }";
  I18n.fallbaks = true

  Flatpickr.localize(Flatpickr.l10ns[I18n.locale]);

app/views/shared/_js_locale.slim
javascript:
  I18n.defaultLocale = "#{ I18n.default_locale }";
  I18n.locale = "#{ I18n.locale }";
  I18n.fallbaks = true

  Flatpickr.localize(Flatpickr.l10ns[I18n.locale]);

app/views/shared/_language_bar.html.slim
li.dropdown.language-bar.hidden-xs
  a.dropdown-toggle data-toggle='dropdown' href='#'
    i class="famfamfam-flag-#{I18n.locale}"
    span.caret
  ul.dropdown-menu
    - (I18n.available_locales - [I18n.locale]).each do |l|
      li
        = link_to locale: l
          i class="famfamfam-flag-#{l}"

app/views/shared/_pagination_with_per_page_links.html.slim
.per_page_links.col-sm-12
  h5
    .small
      strong
        = t('views.pagination.helpers.total_found')
        ':
      =< list.total_count
      .pull-right
        strong
          = t('views.pagination.helpers.per_page')
          ':
        ==< per_page_links list, values: opts[:per_pages], params: opts[:params], remote: opts[:remote], joiner: ' / '
.paginator
  = paginate list, params: opts[:params] || {}, remote: opts[:remote]

app/views/shared/_search_field.html.slim
- path = url_for resource
- search = "#{resource}_search"

input.form-control class="search #{search}" type='text' placeholder="#{t 'gen.search'}"

- content_for :js_footer do
  javascript:
    new Search({ el: $(".#{search}"), url: "#{path}", with_params: ['per'] })

app/views/shared/_user_bar.html.slim
- if user_signed_in?
  li.dropdown
    a.dropdown-toggle data-toggle='dropdown' href='#'
      i.fa.fa-user-circle.fa-inverse.fa-lg
      '
      = current_user.login
      '
      span.caret
    ul.dropdown-menu
      li= link_to settings_path
        i.fa.fa-cog
        '
        = t 'gen.settings'
      li= link_to destroy_user_session_path, method: :delete
        i.fa.fa-power-off
        '
        = t 'views.user.sign_out'
- else
  li= link_to '#', type: 'button', data: { toggle: 'modal', target: '#user-login' }
    i.fa.fa-sign-in
    '
    = t 'views.user.sign_in'

- content_for :html_footer do
  - unless user_signed_in?
    .modal.fade id='user-login' tabindex='-1'
      .modal-dialog
        .modal-content
          .modal-header
            .button.close data-dismiss='modal'
              | &times;
            h4.modal-title
              = t 'views.user.sign_in_title'

          .modal-body.sign-in-form
            = render 'sessions/form'

- content_for :js_footer do
  - unless user_signed_in?
    javascript:
      $('#user-login').on('hidden.bs.modal', function (){
        $('.modal-flash-messages').html('');
        $('#user_password').val('');
      });

      new Turbofix({ onvisit: function() { $('#user-login').html('') } })

app/views/shared/_user_nav.html.slim
- if user_signed_in?
  li= link_to destroy_user_session_path, method: :delete
    i.fa.fa-sign-in
    '
    = t 'views.user.sign_out'
- else
  li= link_to '#', type: 'button', data: { toggle: 'modal', target: '#user-login' }
    i.fa.fa-sign-out
    '
    = t 'views.user.sign_in'

- content_for :html_footer do
  - unless user_signed_in?
    .modal.fade id='user-login'
      .modal-dialog
        .modal-content
          .modal-header
            .button.close data-dismiss='modal'
              | &times;
            h4.modal-title
              = t 'views.user.sign_in_title'

          .modal-body.sign-in-form
            = render 'sessions/form'

- content_for :js_footer do
  - unless user_signed_in?
    javascript:
      $('#user-login').on('hidden.bs.modal', function (){
        $('.modal-flash-messages').html('');
        $('#user_password').val('');
      });

      new Turbofix({ onvisit: function() { $('#user-login').html('') } })