config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords, :sessions]
  as :user do
    post 'sign_in', to: 'sessions#create', as: :user_session
    delete 'sign_out', to: 'sessions#destroy', as: :destroy_user_session
    get 'settings', to: 'users#settings'
    get 'update_password', to: 'users#settings'
    patch 'update_password', to: 'users#update_password'
  end

  resources :tournaments do
    resources :groups, shallow: true
  end

  resources :groups do
    member do
      put 'update_teams'
      get 'search_teams'
    end
  end

  resources :teams do
    put 'update_players', on: :member
  end

  resources :players do
    get 'autocomplete', on: :collection
  end

  resources :faqs, except: [:show] do
    put 'order', on: :collection
  end

  get 'sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

  resources :pages, except: [:index, :show]
  get '/:id', to: 'pages#show', as: :to_page

  root to: 'tournaments#index'
end

app/models/player.rb
class Player < ApplicationRecord
  include ModelExtensions::Avatar

  has_and_belongs_to_many :teams, -> { distinct }
  has_many :goals

  validates_presence_of :fio
  validates_uniqueness_of :fio

  scope :fio_like, ->(fio) { where('players.fio ~* ?', ".*#{fio}.*") }

  has_avatar styles: {thumb: '300x300#'}, default_url: "/images/default_avatar.png"
end

app/models/trail/player.rb
class Trail::Player < Player
  self.table_name = 'trail_players'

  belongs_to :player, optional: true
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :store_per_page, only: [:index]
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    scope = Player.order(:fio)
    scope = scope.fio_like(params[:search]) if params[:search]
    @players = scope.page(params[:page]).per(params[:per])
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: t('controllers.player.create') }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: t('controllers.player.update') }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: t('controllers.player.destroy') }
      format.json { head :no_content }
    end
  end

  def autocomplete
    players = []
    players = Player.order(:fio).fio_like(params[:q]).limit(15) if params[:q].present?
    render json: players.map { |p| {id: p.id, fio: p.fio, avatar: p.avatar.url(:thumb)} }
  end

  private
    def set_player
      @player = Player.find params[:id]
    end

    def player_params
      params.require(:player).permit(:avatar, :fio, :bio, :degree, :graduation_year, :crop_x, :crop_y, :crop_w, :crop_h, :crop_r)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.slim
= bootstrap_form_for @player, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-10', html: {multipart: true} do |f|
  .col-md-4
    = render 'shared/avatar_chooser', form: f, model: @player
  .col-md-7.col-md-offset-1
    = f.text_field :fio, autofocus: true, placeholder: t('views.players.edit.placeholders.fio')
    = f.text_area :bio, rows: 4, placeholder: t('views.players.edit.placeholders.bio')
    = f.text_field :degree, placeholder: t('views.players.edit.placeholders.degree', year: Date.today.year)
    = f.select :graduation_year, options_for_select((1980..Date.today.year + 7).to_a.reverse.unshift(nil), @player.graduation_year), control_col: 'col-sm-2 col-md-3'
    = f.form_group do
      = f.submit t('helpers.links.save'), class: 'btn btn-primary'
      = link_to t('.cancel', default: t('helpers.links.cancel')), players_path, class: 'btn'

- content_for :js_footer do
  javascript:
    var substringMatcher = function(strs) {
      return function findMatches(q, cb) {
        var matches = [];

        $.each(strs, function(i, str) {
          if (str.toLowerCase().startsWith(q.toLowerCase())) {
            matches.push(str);
          }
        });

        cb(matches);
      };
    };

    $('#player_degree').typeahead(
      { minLength: 0 },
      { source: substringMatcher(I18n.t('views.players.degrees'))}
    );

app/views/players/_list.html.slim
= hidden_field_tag :per, params[:per]

- if players.present?
  - players.each do |player|
    .card.col-xs-12.col-sm-6.col-md-3
      .thumbnail
        = link_to player_path(player) do
          .avatar-container style="padding-bottom:#{player.aspect_ratio(:thumb)}%"
            = image_tag player.avatar.url(:thumb), class: 'avatar img-rounded'
          .text-center
            h4.single-line = player.fio
            - if player.degree.present?
              h5
                small
                  => player.degree
                  =<> "( #{ player.graduation_year } )" if player.graduation_year.present?
            - else
              p style='height:15px'
        - if can? :manage, Player
          hr.ball
          .admin_panel.actions
            = render "#{controller_path}/player_actions", player: player

app/views/players/_player_actions.html.slim
.text-center
  => link_to edit_player_path(player), class: 'btn btn-circle', title: t('views.players.tooltips.edit')
    = edit_glyph

  => link_to player_path(player), class: 'btn btn-red btn-circle', method: :delete,
    data: { confirm: t('views.players.confirm_delete') }, title: t('views.players.tooltips.delete')
    = delete_glyph

app/views/players/_players.html.slim
- unless @players.present?
  | No players found
- @players.each do |player|
  .col-xs-12.col-sm-6.col-md-3
    .thumbnail
      = link_to image_tag(player.avatar.url :thumb), player_path(player)
      .caption
        h4.text-center= player.fio
        p= truncate player.bio
        => link_to t('.edit', default: t("helpers.links.edit")), edit_player_path(player), class: 'btn btn-default btn-xs'
        = link_to t('.destroy', default: t("helpers.links.destroy")), player_path(player), method: :delete, data: { confirm: t('.confirm', default: t('helpers.links.confirm', default: 'Are you sure?')) }, class: 'btn btn-xs btn-danger'

app/views/players/edit.html.slim
- breadcrumb :player, @player

.page-header
  h1
    =t 'views.players.edit.title'
    .pull-right
      = players_header_glyph
= render partial: "form"

app/views/players/index.html.slim
- resource = Player.model_name.plural
.page-header
  h1
    =t 'gen.players'
    .pull-right
      = players_header_glyph

.control-bar
  - if can? :create, Player
    .actions.pull-right
      = link_to new_player_path, class: 'btn btn-circle', title: t('views.players.tooltips.new')
        = add_glyph
  .col-xs-10.col-sm-6.col-md-4.input-group
    = render 'shared/search_field', resource: resource

.row id="#{resource}"
  = render 'list', players: @players

.row.remote_pagination
    = render 'shared/pagination_with_per_page_links', list: @players, opts: {params: params.slice(:search).to_unsafe_h, remote: true}

app/views/players/index.js.slim
| $('#players').html('
= j render 'list', players: @players
|');

| $('.remote_pagination').html('
= render 'shared/pagination_with_per_page_links', list: @players, opts: { params: params.slice(:search).to_unsafe_h, remote: true }
| ');

app/views/players/new.html.slim
- breadcrumb :new_player

.page-header
  h1
    =t 'views.players.new.title'
    .pull-right
      = players_header_glyph

= render partial: "form"

app/views/players/show.html.slim
- breadcrumb :player, @player

- model_class = Player
.page-header
  h1
    .pull-right
      = players_header_glyph
    = @player.fio

.actions
  => link_to players_path, class: 'btn btn-circle', title: t('views.players.tooltips.index')
    = back_glyph
  - if can? :manage, Player
    .pull-right
      => link_to edit_player_path(@player), class: 'btn btn-circle', title: t('views.players.tooltips.edit')
        = edit_glyph

      => link_to player_path(@player), class: 'btn btn-red btn-circle', method: :delete,
        data: { confirm: t('views.players.confirm_delete') }, title: t('views.players.tooltips.delete')
        = delete_glyph

      => link_to new_player_path, class: 'btn btn-circle', title: t('views.players.tooltips.new')
        = add_glyph

br

.card
  .thumbnail
    .col-sm-5
      = link_to_image @player.avatar.file?, @player.avatar.url,
        image_tag(@player.avatar.url(:thumb), class: 'img-rounded img-responsive center-block'),
        data: { toggle: 'lightbox' }

    .col-sm-7
      h4
        -if @player.graduation_year.present?
          .pull-right
            h5 style='margin-top: 0px'
              small
                =<> t('views.players.show.graduation_year', year: @player.graduation_year)
        = @player.degree

      = @player.bio
    .clearfix